name: BuildAll

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
        architecture: 'x64'
    - uses: nttld/setup-ndk@v1.0.6
      with:
        ndk-version: r21e
    - uses: actions/checkout@v2
    
    - name: Get version
      uses: KageKirin/get-node-package-version@v0
      id: package_version
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'gradle'
        
    - uses: actions/setup-node@v2
      with:
        node-version: '17.1.0'
        cache: 'yarn'
        
    - run: yarn
    - run: cd android && ./gradlew bundleRelease && cd ..
    
    - name: install bundletool
      uses: enniel/bundletool-runner@v1.1.0
    
    - run: bundletool build-apks --mode=universal --bundle=./android/app/build/outputs/bundle/release/app-release.aab --output=./android/app/build/outputs/bundle/release/app-release.apks
    - run: mv ./android/app/build/outputs/bundle/release/app-release.apks ./android/app/build/outputs/bundle/release/app-release-apk.zip
    
    - name: Install hub
      uses: geertvdc/setup-hub@master
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        
    - name: Create changelog text
      id: changelog
      uses: loopwerk/tag-changelog@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: run hub commands
      env:
        GITHUB_USER: ${{ secrets.USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
           hub release create -dp -a android/app/build/outputs/bundle/release/app-release.aab -a android/app/build/outputs/bundle/release/app-release-apk.zip -m "${{ steps.changelog.outputs.changelog }}" ${{ steps.package_version.outputs.version }}-${{ github.run_number }}
      
    #- name: build
    #  run: cd xmrig/lib-builder && mkdir build && mkdir build/src && mkdir build/build && make all
      
