name: Makefile CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
        architecture: 'x64'
    - uses: nttld/setup-ndk@v1.0.6
      with:
        ndk-version: r21e
    - uses: actions/checkout@v2
    
    - name: Get version
      uses: KageKirin/get-node-package-version@v0
      id: package_version
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'gradle'
        
    - uses: actions/setup-node@v2
      with:
        node-version: '17.1.0'
        cache: 'yarn'
        
    - run: yarn
    - run: cd android && ./gradlew bundleRelease && cd ..
    
    - name: Create a Release
      uses: elgohr/Github-Hub-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release create -dp -a android/app/release/app-release.aab ${{ steps.package_version.outputs.version }}
      
    
    #- name: build
    #  run: cd xmrig/lib-builder && mkdir build && mkdir build/src && mkdir build/build && make all
      
