name: Makefile CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
        architecture: 'x64'
    - uses: nttld/setup-ndk@v1.0.6
      with:
        ndk-version: r21e
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - uses: actions/setup-node@v2
      with:
        node-version: '17.1.0'
        cache: 'yarn'
        
    - run: yarn
    - run: cd android && ./gradlew bundleRelease
      
    
    #- name: build
    #  run: cd xmrig/lib-builder && mkdir build && mkdir build/src && mkdir build/build && make all
      
